Centralized JWT Provider (#148)
* Added jwt token verify api endpoint

* Added tests for token verify endpoint

* Added Identity Service URL env variable to workshop and community service

* Chore: Fixed response code for token verify endpoint

* Migrated to using Identity service for token verification in Community service

* Fixed community service build

* Fixed formatting issue

* Migrated to using Identity service for token verification in Workshop service

* Fixed unittests in workshop service

* Fixed response status code of jwt verify endpoint

* Removed JWT_SECRET variable from workshop and community services

* - Added private key for jwt in all deployment methods
- Modified identity service entrypoint to load private key as env variables

* Updated identity service to use user provided private key

* Replaced PEM file with JWKS.json and serving jwks.json from well-known

* Fixed public jwks.json format

* Updated Postman Collections

Co-authored-by: Roshan Piyush <roshan.piyush@traceable.ai>

diff --git a/services/identity/Dockerfile b/services/identity/Dockerfile
--- a/services/identity/Dockerfile
+++ b/services/identity/Dockerfile
@@ -14,8 +14,11 @@
 # Java Maven Build
 FROM gradle:7.3.3-jdk11 AS gradlebuild
 WORKDIR /app
-COPY src src
 COPY *.gradle.kts ./
+# Only download dependencies
+# Eat the expected build failure since no source code has been copied yet
+RUN gradle clean build --no-daemon > /dev/null 2>&1 || true
+COPY src src
 RUN gradle build
 RUN gradle bootJar
 
@@ -32,4 +35,5 @@ EXPOSE ${SERVER_PORT}
 
 ENV JAVA_TOOL_OPTIONS "-Xmx128m"
 
-CMD java -jar /app/identity-service-1.0-SNAPSHOT.jar
+COPY entrypoint.sh /entrypoint.sh
+CMD [ "/entrypoint.sh"]
